source 'https://github.com/RonnieJia/RJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'RJNetworking_Example' do
  pod 'RJNetworking', :path => '../'

  target 'RJNetworking_Tests' do
    inherit! :search_paths

    
  end
end
